[browser]
serverAddress = "localhost"
gatherUsage = false
serverPort = 8501

[theme]
primaryColor="#HEXADECIMAL_COLOR"
backgroundColor="#HEXADECIMAL_COLOR"
secondaryBackgroundColor="#HEXADECIMAL_COLOR"
textColor="#HEXADECIMAL_COLOR"
font="sans serif"
