// Database structure defined with DBML
// Docs: https://dbml.dbdiagram.io/docs

Project Stripe_OLAP {
  database_type: 'PostgreSQL'
  Note: 'Stripe\'s OLAP database proposal'
}


///// Tables /////

Table transactions {
  transaction_id bigint [primary key]
  time_id bigint
  merchant_id bigint
  customer_id bigint
  currency_code Char(3) // ISO 4217
  ip_geo_id bigint
  amount decimal(10, 2)
  payment_method varchar(16)
  payment_status varchar(16)
  device_type varchar(16)
}


Table transaction_time {
  time_id bigint [primary key] 
  timestamp datetime
  timezone integer
  date date
  time time
  year mediumint
  month tinyint
  week_day tinyint
  quarter tinyint
}


Table merchants {
  merchant_id bigint [primary key]
  country_code char(2) // ISO 3166-1 2-letter
  // ...
}

Table customers {
  customer_id bigint [primary key]
  country_code char(2) // ISO 3166-1 2-letter
  // ...
}


Table fraud_indicators {
  transaction_id bigint [primary key]
  fraud_probability float
  // ...
}

Table ip_geography {
  ip_geo_id bigint [primary key]
  latitude float
  longitude float
  country_code char(2) // ISO 3166-1 2-letter
  province varchar(255)
  // ...
}


///// Reference tables /////

Table currencies {
  currency_code char(3) [primary key] // ISO 4217
  currency_name varchar(255) [unique]
  usd_change_rate decimal(6,4)
}

Table countries {
  country_code char(2) [primary key] // ISO 3166-1 alpha-2
  currency_name varchar(255) [unique]
}

Table payment_methods {
  payment_method_id integer [primary key]
  payment_method varchar(16) [unique] // credit_card, ...
}

Table payment_statuses {
  payment_status_id integer [primary key]
  payment_status varchar(16) [unique] // successful, failed, refunded, ...
}

Table device_types {
  device_type_id integer [primary key]
  device_type varchar(16) [unique] // mobile, desktop, ...
}

Table months {
  month tinyint [primary key]
  month_name varchar(9) [unique]
}

Table week_days {
  week_day tinyint [primary key]
  week_day_name varchar(9) [unique]
}


///// Relationships /////

// 1st level
Ref: transactions.time_id > time.time_id
Ref: transactions.merchant_id > merchants.merchant_id
Ref: transactions.customer_id > customers.customer_id
Ref: transactions.currency_id > currencies.currency_id
Ref: transactions.ip_geo_id > ip_geography.ip_geo_id
Ref: transactions.transaction_id - fraud_indicators.transaction_id

// 2nd level
Ref: merchants.country_id > countries.country_id
Ref: customers.country_id > countries.country_id
Ref: ip_geography.country_id > countries.country_id

// Relations to ref tables
Ref: transactions.payment_method > payment_methods_ref.payment_method
Ref: transactions.payment_status > payment_statuses_ref.payment_status
Ref: transactions.device_type > device_types_ref.device_type
Ref: time.month > months_ref.month
Ref: time.week_day > week_days_ref.week_day